version: "2"

services:
  database:
    image: mariadb
    container_name: database
    hostname: database
    networks:
      - custom_net
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: joomla
  
  phpmyadmin:
    build:
      context: PhpMyAdmin
    container_name: my-phpmyadmin 
    depends_on:
     - database
    networks:
      - custom_net
    environment:
      DB_HOST: database 
      DB_USER: root
      DB_PASSWORD: admin

  joomla: 
    build:
      context: Joomla
    container_name: my-joomla
    depends_on:
     - database
    networks:
      - custom_net
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: joomla
      JOOMLA_ADMIN_USER: admin
      JOOMLA_ADMIN_PASS: admin
      JOOMLA_ADMIN_EMAIL: admin@admin.it
 
  proxy:
    build:
      context: Proxy
    container_name: proxy
    depends_on:
      - joomla
      - phpmyadmin
    ports:
      - "80:80"
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
