version: "3"

networks:
  custom_net:
    driver: overlay

services:
  database:
    image: mariadb
    hostname: database
    networks:
      - custom_net
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: joomla

  phpmyadmin:
    image: custom-phpmyadmin:latest
    depends_on:
     - database
    networks:
      - custom_net
    environment:
      DB_HOST: database 
      DB_USER: root
      DB_PASSWORD: admin

  joomla: 
    image: custom-joomla:latest
    depends_on:
     - database
    networks:
      - custom_net
    volumes:
      - /gfs/joomla-volume/components:/var/www/html/components
      - /gfs/joomla-volume/administrator:/var/www/html/administrator
      - /gfs/joomla-volume/images:/var/www/html/images
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: joomla
      JOOMLA_ADMIN_USER: admin
      JOOMLA_ADMIN_PASS: admin
      JOOMLA_ADMIN_EMAIL: admin@admin.it
    deploy:
      mode: global
   
  prometheus:
    image: custom-prometheus:latest
    deploy:
      mode: global
    depends_on:
      - database
      - joomla
      - phpmyadmin
    networks:
      - custom_net

  grafana:
    image: custom-grafana:latest
    depends_on:
      - prometheus
    networks:
      - custom_net

  proxy:
    image: custom-proxy:latest
    depends_on:
      - joomla
      - phpmyadmin
    networks:
      - custom_net
    ports:
      - 80:80
    deploy:
      mode: global  

  cadvisor:
    image: google/cadvisor
    deploy:
      mode: global
    networks:
      - custom_net

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    networks:
      - custom_net
