version: "2"

services:
 database:
  image: mariadb
  network_mode: bridge
  container_name: database
  hostname: database
  environment:
   MYSQL_ROOT_PASSWORD: user
   MYSQL_DATABASE: joomla

 joomla: 
  image: my-joomla
  network_mode: bridge
  container_name: my-joomla
  ports: 
   - "80:80"
  environment:
   DB_HOST: 172.17.0.4
   DB_USER: root
   DB_PASSWORD: user
   DB_NAME: joomla
