version: "3"

services:
  database:
    image: mariadb
    hostname: database
    networks:
      - custom_net
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: joomla

  phpmyadmin:
    image: custom-phpmyadmin:latest
    #deploy:
    #  mode: replicated
    #  replicas: 3
    depends_on:
     - database
    networks:
      - custom_net
    ports:
      - 4000:80
    environment:
      DB_HOST: database 
      DB_USER: root
      DB_PASSWORD: admin

  joomla: 
    image: custom-joomla:latest
    depends_on:
     - database
    networks:
      - custom_net
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: joomla
      JOOMLA_ADMIN_USER: admin
      JOOMLA_ADMIN_PASS: admin
      JOOMLA_ADMIN_EMAIL: admin@admin.it
    deploy:
      mode: replicated
      replicas: 3
   
  prometheus:
    image: custom-prometheus:latest
    depends_on:
      - database
      - joomla
      - phpmyadmin
    networks:
      - custom_net

  grafana:
    image: custom-grafana:latest
   # deploy:
   #   mode: replicated
   #   replicas: 3
    depends_on:
      - prometheus
    networks:
      - custom_net   
    ports:
      - 3000:3000   

  proxy:
    image: custom-proxy:latest
    depends_on:
      - joomla
      - phpmyadmin
    networks:
      - custom_net
    ports:
      - 80:80
   # deploy:
   #   mode: replicated
   #   replicas: 3
  

  cadvisor:
    image: google/cadvisor
    deploy:
      mode: global
    networks:
      - custom_net

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    networks:
      - custom_net


networks:
  custom_net:
    driver: overlay
